[package]
name = "loader"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64.workspace = true
log.workspace = true
thiserror.workspace = true
framebuf.workspace = true
uefi = { version = "0.37.0", features = ["global_allocator", "alloc", "panic_handler"] }
goblin = { version = "0.10.7", features = ["elf64", "elf32", "endian_fd"], default-features=false }
